spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

  datasource:
    url: jdbc:h2:~/testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  
  h2:
    console:
      enabled: true
      path: /h2-console

  jooq:
    sql-dialect: h2

  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql

logging:
  level:
    sql: DEBUG